version: "3.8"

services:
  server:
    build: ./apps/server
    container_name: mixmatch-server
    ports:
      - "8080:8080"

  hub:
    build: ./apps/hub
    container_name: mixmatch-hub
    ports:
      - "3001:3000" # maps container port 3000 to host port 3001
    depends_on:
      - server

  player:
    build: ./apps/player
    container_name: mixmatch-player
    ports:
      - "3002:3000" # maps container port 3000 to host port 3002
    depends_on:
      - server
