services:
  server:
    build: ./apps/server
    container_name: mixmatch-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  hub:
    build: ./apps/hub
    container_name: mixmatch-hub
    ports:
      - "3001:3000" # host:container
    env_file:
      - .env
    depends_on:
      - server

  player:
    build: ./apps/player
    container_name: mixmatch-player
    ports:
      - "3002:3000" # host:container
    env_file:
      - .env
    depends_on:
      - server