services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"

  hub:
    build:
      context: .
      dockerfile: apps/hub/Dockerfile
    working_dir: /app
    command: >
      sh -lc "CI=true pnpm install &&
              pnpm approve-builds &&
              pnpm --filter ./apps/hub dev --host 0.0.0.0 --port 5173 --strictPort"
    environment:
      - CI=true
      - VITE_SERVER_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./apps/hub:/app/apps/hub
      - ./packages/shared:/app/packages/shared
      - root_node_modules:/app/node_modules
    depends_on: [server]

  player:
    build:
      context: .
      dockerfile: apps/player/Dockerfile
    working_dir: /app
    # wait until node_modules exists, then start dev (no install here)
    command: >
      sh -lc "until [ -d node_modules ]; do echo 'waiting for node_modules...'; sleep 0.5; done;
              pnpm --filter ./apps/player dev --host 0.0.0.0 --port 5173 --strictPort"
    environment:
      - VITE_SERVER_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    ports:
      - "5174:5173"
    volumes:
      - ./apps/player:/app/apps/player
      - ./packages/shared:/app/packages/shared
      - root_node_modules:/app/node_modules
    depends_on: [server, hub]

volumes:
  root_node_modules: {}
