services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env

  hub:
    build:
      context: .
      dockerfile: apps/hub/Dockerfile
    working_dir: /app
    command: >
      sh -lc "CI=true pnpm install &&
              pnpm approve-builds &&
              pnpm --filter ./apps/hub dev --host 0.0.0.0 --port 5173 --strictPort"
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
      - VITE_SPOTIFY_CLIENT_ID=${VITE_SPOTIFY_CLIENT_ID}
    ports:
      - "5173:5173"
    volumes:
      - ./apps/hub:/app/apps/hub
      - ./packages/shared:/app/packages/shared
      - root_node_modules:/app/node_modules
    depends_on: [server]

  player:
    build:
      context: .
      dockerfile: apps/player/Dockerfile
    working_dir: /app
    command: >
      sh -c "pnpm install &&
             pnpm --filter ./apps/player dev --host 0.0.0.0 --port 5173 --strictPort"
    environment:
      - VITE_SERVER_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    ports:
      - "5174:5173"
    volumes:
      - ./apps/player:/app/apps/player
      - ./packages/shared:/app/packages/shared
      - root_node_modules:/app/node_modules
    depends_on: [ server, hub ]

volumes:
  root_node_modules: {}
